###
GET http://localhost:8080/home

###
POST http://localhost:8080/home
Content-Type: application/json

"some body"

###
GET http://localhost:8080/

###
GET http://localhost:8080/test1/test1
Authorization: Basic {{username}} {{password}}

###
GET http://localhost:8080/test1/test2
Authorization: Basic {{username}} {{password}}


###master
GET http://localhost:8080/test2/test/test2
Authorization: Basic {{username}} {{password}}
###master
GET http://localhost:8080/test2/test1
Authorization: Basic {{username}} {{password}}
###guest
GET http://localhost:8080/foo/test3
Authorization: Basic {{username}} {{password}}
###guest
GET http://localhost:8080/bar/test/test3
Authorization: Basic {{username}} {{password}}
###